import 'dart:core';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:youtube/Post/post4.dart';
import 'package:youtube/Post/postmain.dart';
import 'model.dart';

class Post3 extends StatefulWidget {
  @override
  State<Post3> createState() => _Post3State();
}

class _Post3State extends State<Post3> {
  final List<Map<String, dynamic>> _items = [
    {
      'title': 'Ajloun',
      'color': Colors.blueGrey,
      'region': [
        'A\'anjara',
        'A\'fna',
        'Al-Hashimiyyah',
        'Alqala\'a',
        'Barqash',
        'Downtown',
        'E\'in Jana',
        'L\'bbeen',
        'Kuforanja',
        'Sakhra',
        'Other',
      ]
    },
    {
      'title': 'Alkarak',
      'color': Colors.blueGrey,
      'region': [
        'A\'i',
        'Ader',
        'Al-Adnanya',
        'Al-Marj',
        'Al-Mazar Al-Janoubi',
        'Al-Qasr',
        'Al-Qatraneh',
        'Al-Rabba',
        'Al-Smeikhiyyeh',
        'Al-Thaniyyah',
        'Al Msherifeh',
        'Manshiyyet Abu Hammour',
        'Mu\'ta',
        'Qusoor Bashir',
        'That Ras',
        'Zohoom',
        'Other',
      ]
    },
    {
      'title': 'Amman',
      'color': Colors.blueGrey,
      'region': [
        '1st Circle',
        '2nd Circle',
        '3rd Circle',
        '4th Circle',
        '5th Circle',
        '6th Circle',
        '7th Circle',
        '8th Circle',
        'Abdali',
        'Abdoun',
        'Abu Al-Sous',
        'Abu Alanda',
        'Abu Nsair',
        'Dunes Bridge',
        'Madaba Bridge',
        'Manaseer Gs',
        'Nakheel Village',
        'Al-Adlyeh',
        'Al-Amir Hamzah',
        'Al-Awdeh',
        'Al-Dia\'',
        'Al-Diyar',
        'Al-Feisal',
        'Al-Fuhais',
        'Al-Jabal Al-Akhdar',
        'Al-Jweideh',
        'Al-Khaznah',
        'Al-Kom Al-Gharbi',
        'Al-Kom Al-Sharqi',
        'Al-Ma\'adi',
        'Al-Mansour',
        'Al-Mustanada',
        'Al-Muwaqqar',
        'Al-Naharyah',
        'Al-Oroubah',
        'Al-Qasabat',
        'Al-Qusour',
        'Al-Rabwa',
        'Al-Rjoum',
        'Al-Shabah',
        'Al-Thra',
        'Al-Thuheir',
        'Al-Wehdat',
        'Al-Yarmouk',
        'Al-Zahra',
        'Al Ashrafyeh',
        'Al Bayader',
        'Al Bnayyat',
        'Al Gardens',
        'Al Hashmi Al Janobi',
        'Al Hashmi Al Shamali',
        'Al Hummar',
        'Al Hurryeh',
        'Al Jandaweel',
        'Al Jizah',
        'Al Kamaliya',
        'Al Kursi',
        'Al Lubban',
        'Al Manarah',
        'Al Muqabalain',
        'Al Qastal',
        'Al Qwaismeh',
        'Al Rabiah',
        'Al Rajeeb',
        'Al Rawabi',
        'Al Rawnaq',
        'Al Ridwan',
        'Al Sahl',
        'Al Sina\'a',
        'Al Tuneib',
        'Al Urdon Street',
        'Al Yadudah',
        'Arjan',
        'Ayn Rbat',
        'Badr',
        'Badr Jdedeh',
        'Baqa\'a Camp',
        'Basman',
        'Bilal',
        'Birayn',
        'Dabouq',
        'Daheit Al-Haj Hassan',
        'Daheit Al Ameer Hasan',
        'Daheit Al Aqsa',
        'Daheit Al Rasheed',
        'Daheit Al Yasmeen',
        'Daheit Al Ameer Ali',
        'Daheit Al Ameer Rashed',
        'Daheit Al Hussain',
        'Deir Ghbar',
        'Downtown',
        'Hai Nazzal',
        'Hay Al Rahmanieh',
        'Hay Albarakeh',
        'Hay AlKhaledeen',
        'Hay Alsaleheen',
        'Hettin',
        'Hjar Al Nawailseh',
        'Husban',
        'Iraq Al Ameer',
        'Jabal Al-Jofah',
        'Jabal Al-Lweibdeh',
        'Jabal Al-Marrikh',
        'Jabal Al-Nathif',
        'Jabal Al-Taj',
        'Jabal Al Hussain',
        'Jabal Al Naser',
        'Jabal Al Nuzha',
        'Jabal Al Zohor',
        'Jabal Amman',
        'Jawa',
        'Jubaiha',
        'Khalda',
        'Khirbet Sooq',
        'Mahes',
        'Marj El Hamam',
        'Marka',
        'Mecca Street',
        'Medina Street',
        'Naour',
        'Rajm Amesh',
        'Ras El Ain',
        'Rujm ash Shami',
        'Safut',
        'Sahab',
        'Salem',
        'Salihiyat Al-Abid',
        'Shafa Badran',
        'Shmaisani',
        'Sports City',
        'Swefieh',
        'Swelieh',
        'Tabarboor',
        'Tla\'Ali',
        'Tloo\'Al-Misdar',
        'Um al Basateen',
        'Um El Summaq',
        'Um Rummanah',
        'Um Uthaiena',
        'Umm al Kundum',
        'Umm Al-Usoud',
        'Umm Nowarah',
        'Umm Shterat',
        'University Street',
        'Uyun Al-Dhib',
        'Wadi Al-Srour',
        'Wadi Al Haddadeh',
        'Wadi El Seer',
        'Wadi Saqra',
        'Yajouz',
        'Other',
      ]
    },
    {
      'title': 'Aqaba',
      'color': Colors.blueGrey,
      'region': [
        'Al-Alamiya',
        'Al-Markaziya',
        'Al-Nakhil',
        'Al-Sakaneyeh 8',
        'Al-Sakaneyeh',
        'Al-Shamiyah',
        'Al Atiba\'',
        'Al Balad Al Qadeemeh',
        'Al Herafeyeh',
        'Al Mahdood Al Gharby',
        'Al Mahdood Al Sharqy',
        'Al Mahdood Al Wasat',
        'Al Manarah',
        'Al Mulqan',
        'Al Ridwan',
        'Al Rimaal',
        'Al Sakaneyeh (10)',
        'Al Sakaneyeh (3)',
        'Al Sakaneyeh (5)',
        'Al Sakaneyeh (6)',
        'Al Sakaneyeh (7)',
        'Al Sakaneyeh (9)',
        'Al Shalalah',
        'Karama',
        'Mulqan Janoubi',
        'Mulqan Shamali',
        'Qweira',
        'Sakan Al Asmedah',
        'Tala Bay',
        'Wadi Rum',
        'Other',
      ]
    },
    {
      'title': 'Irbid',
      'color': Colors.blueGrey,
      'region': [
        '30 Street',
        'Abu Sidu',
        'Al-Adasiya',
        'Al-Baqoura',
        'Al-Kharaj',
        'Al-Mahari\'a',
        'Al-Manshiya',
        'Al-Mughayer',
        'Al-Tal',
        'Al-Zamaliya',
        'Al Afrah',
        'Al Andalus',
        'Al Ashrafiyah',
        'Al Balad',
        'Al Barha',
        'Al Barha Street',
        'Al Dorra Circle',
        'Al Eiadat Circle',
        'AlHashmy',
        'Al Hay Al Gharby',
        'Al Hay Al Janooby',
        'Al Hay Al Sharqy',
        'Al Hisbeh Al Markizeya',
        'Al Husn',
        'Al Huson Street',
        'Al Lawazem Circle',
        'Al Madinah Al Sena\'eiah',
        'Al Madrase Al Shamela',
        'Al Mal\'ab Al Baladi',
        'AlMatla\'',
        'Al Mazer Al-Shamali',
        'Al Naseem Circle',
        'Al Nuzha',
        'Al Qubeh Circle',
        'Al Quds Street',
        'Al Rabiah',
        'Al Rahebat Al Wardiah',
        'Al Sareeh',
        'Al Sonbola',
        'Al Souq',
        'Al Thaqafa Circle',
        'Albayyada Circle',
        'An-Nuayyimah',
        'Arhaba',
        'Aydoun',
        'Bait Ras',
        'Basila',
        'Bayt ldis',
        'Behind Safeway',
        'Bushra',
        'Daheit Al Ameer Rashed',
        'Daheit Al Hussain',
        'Dayr as Si\'nah',
        'Der Abi Saeed',
        'Eidoon Military Hospital',
        'Fo\'ara Street',
        'Ghorfat Al Tejara',
        'Hakama',
        'Hakama Street',
        'Hartha',
        'Hasan Al Tal Mosque',
        'Hatim village',
        'Hay Al Abraar',
        'Hay Al Qaselah',
        'Hay Al Turokman',
        'Hay Al Worood',
        'Hay Al Zohoor',
        'Hay Alia',
        'Hay Altlool',
        'Hay Twaal',
        'Hofa',
        'Honaina',
        'Howara',
        'Inba',
        'Irbid Girl\'s College',
        'Irbid Mall',
        'Isharet Al Darawshe',
        'Isharet Al Iskan',
        'Isharet Al Malika Noor',
        'Iskan Al A\'mileen',
        'Iskan Al Atiba\'',
        'Iskan Al Dobbat',
        'Iskan Al Mohandeseen',
        'Judayta',
        'Kharja',
        'Kherbet Qasem',
        'King Abdullah University Hospital',
        'Kofor Youba',
        'Kufr Abeel',
        'Kufr Asad',
        'Kufr Awan',
        'Kufr Ma\'',
        'Kufr Rakeb',
        'Kufr Sown',
        'Kuraimah',
        'Makhraba',
        'Malka',
        'Mandah',
        'Maru',
        'Mojamma\' Al Aghwaar Al Jadeed',
        'Mojamma\' Al Shamal',
        'Mojamma\' Alshaikh Khaleel',
        'Mojamma\' Amman Al Jadeed ',
        'North Shuna',
        'Palestine Street',
        'Petra Street',
        'Princess Basma Hospital',
        'Qum',
        'Qumaym',
        'Sahara Circle',
        'Sahm',
        'Saidour',
        'Sal Circle',
        'Salet Al Sharq',
        'Samad',
        'Sammou',
        'Marka',
        'Mecca Street',
        'Seil Al-Himma',
        'Shajara',
        'Sharekat Al Kahraba Circle',
        'Shatna',
        'Shaykh Hussein',
        'Smma',
        'Tabaqet Fahel',
        'Taybeh District',
        'Tibneh',
        'University of Science and Technology',
        'University Street',
        'Wadi Al-Rayyan',
        'Waqqas',
        'Zabda',
        'Zubiya',
        'Other',
      ]
    },
    {
      'title': 'Jerash',
      'color': Colors.blueGrey,
      'region': [
        'Al-Haddadeh',
        'Al-Hashimiyyah',
        'Al-Kittah',
        'Al-Majdal',
        'Al-Mastaba',
        'Al-Msherifeh',
        'Al-Naseem',
        'Al-Rashaida',
        'Amamah',
        'Borma',
        'Dahl',
        'Debbin',
        'Kufair',
        'Kufor Khal',
        'Marsa\'',
        'Qafqafa',
        'Sakib',
        'Salhoub',
        'Soof',
        'Tal Al-Rumman',
        'Unaybah',
        'Other',
      ]
    },
    {
      'title': 'Maan',
      'color': Colors.blueGrey,
      'region': [
        'Al-Hussainiyyah',
        'Al-Mraigha',
        'Al-Shobak',
        'Ayl',
        'Bayda',
        'Jafr',
        'Jaya',
        'Ma\'an Qasabah',
        'Najl',
        'Petra',
        'Sath Ma\'an',
        'Shmakh',
        'Um Sayhoon',
        'Wadi Musa',
        'Other',
      ]
    },
    {
      'title': 'Madaba',
      'color': Colors.blueGrey,
      'region': [
        'Al-Faisaliyyah',
        'Al-Fayha\'',
        'Al-Jbeil',
        'Al-Mokhayam',
        'Al-Zafaran',
        'Dalilet Al-Hamaideh',
        'Hanina',
        'Hanina Al-Gharbiyyah',
        'Jelul',
        'lob',
        'Madaba Center',
        'Mai\'n',
        'Manja',
        'Mkawer',
        'Thiban',
        'Umm Al Amad',
        'Other',
      ]
    },
    {
      'title': 'Mafraq',
      'color': Colors.blueGrey,
      'region': [
        'Ain wa Al-Ma\'mariyyeh',
        'Al-Ba\'ij',
        'Al-Badiah Ash-Shamaliyah',
        'Al-Badiah Ash-Shamaliyah Al-Gharbiya',
        'Al-Bustan',
        'Al-Dafyana',
        'Al-Dajaniya',
        'Al-Daqusma',
        'Al-Hamra',
        'Al-Hey Al-Hashmi',
        'Al-Hey Al-Janoubi',
        'Al-Khalidya',
        'Al-Khirba Al-Samra',
        'Al-Mabruka',
        'Al-Marajim',
        'Al-Mazraa',
        'Al-Nithamiya',
        'Al-Rashada',
        'Al-Rfa\'iyat',
        'Al-Salhiya',
        'Al-Za\'atari',
        'Al-Zaytouna',
        'Al Ghadeer Al Abyad',
        'Al Mazzeh',
        'Bala\'ama',
        'Bowaydet Al Hawamdeh',
        'Bweida Al-Ilimat',
        'Dahiyat Al-Jamaa',
        'Dahl',
        'Dayr Al-kahf',
        'Fa\'',
        'Hai Nowarah',
        'Hawshah',
        'Hay Al-Dobbat',
        'Hay Al-Hussein',
        'Hay Al-Zohoor',
        'Hayyan Al Moshref',
        'Hayyan Rwaibed',
        'Hweishan',
        'Idoun',
        'Koum Al-Ahmar',
        'Manshiyyet Bani Hassan',
        'Mansoura',
        'Mughayyer Al-Sarhan',
        'Nadira',
        'Nayfa',
        'rahbat Rakad',
        'Rhab',
        'Ruwaished',
        'Sabha',
        'Safawi',
        'Sama As-Sirhan',
        'Tayeb Isim',
        'Thaghrat Al-Gub',
        'Um Al-Lula',
        'Um Al Jimal',
        'Um Al Na\'am Al Gharbiyyeh',
        'Um Al Na\'am Al Sharqiyyeh',
        'Um Batima',
        'Um Sweiweina',
        'Umm Al-Quttayn',
        'Zamlat Al-Amir Ghazi',
        'Znaya',
        'Other',
      ]
    },
    {
      'title': 'Salt',
      'color': Colors.blueGrey,
      'region': [
        'A\'llan',
        'Abu Nsair',
        'Al Balqa\'',
        'Al I\'zariyyeh',
        'Al Jada\'a',
        'Al Jadoor',
        'Al Khader',
        'Al Khandaq',
        'Al Maghareeb',
        'Al Manshiyyeh',
        'Al Midan',
        'Al NAqab',
        'Al Qala\'a',
        'Al Remeimeen',
        'Al Salalem',
        'Al Saro',
        'Al Sawarfeh',
        'Al Subeihi',
        'Al Zohour',
        'Ein Al-Basha',
        'Hay Al Kharabsheh',
        'I\'ra',
        'Jala\'d',
        'Kafr Hooda',
        'Naqb Al Daboor',
        'Seehan',
        'Shafa Al-Amriya',
        'South Shuna',
        'Swemeh',
        'Um Jozeh',
        'Wadi Shua\'ib',
        'Yarga',
        'Zay',
        'Other',
      ]
    },
    {
      'title': 'Tafila',
      'color': Colors.blueGrey,
      'region': [
        'A\'llan',
        'Al-Ayes',
        'Al-Hasa',
        'Al-Qadisiyyah',
        'Al-Qasr',
        'Al-Rashadiyyah',
        'Bseira',
        'Dana',
        'Jurf Al-Daraweesh',
        'Other',
      ]
    },
    {
      'title': 'Zarqa',
      'color': Colors.blueGrey,
      'region': [
        'Abu Al-Zighan',
        'Al-Alouk',
        'Al-Kamsha',
        'Al-Misfat st.',
        'Al-Qadisyeh - Rusaifeh',
        'Al-Qnaiya',
        'Al-Saadeh st.',
        'Al Autostrad',
        'Al ghweariyyeh',
        'Al Hashemieh',
        'Al Hawooz',
        'Al Jaish Street',
        'Al mantika Al Hurra',
        'Al Souq',
        'Al Sukhneh',
        'Al Tatweer Al Hadari',
        'Al Tatweer Al Hadari Rusaifah',
        'Al Zarqa Al Jadeedeh',
        'Al Zawahra',
        'Awajan',
        'Azraq',
        'Birayn',
        'Daheit Makka Al-Mokarameh',
        'Daheit Al Amera Haya',
        'Daheit Al Madena Al Monawwara',
        'Dhlail',
        'Douqara',
        'Graiba',
        'Graisa',
        'Hay Al-Rasheed - Rusaifah',
        'Hay Al Ameer Mohammad',
        'Hay Al Hussain',
        'Hay Al Iskan',
        'Hay Al Jundi',
        'Hay Al Nuzha',
        'Hay Ja\'far Al-Tayyar',
        'Hay Ma\'ssom',
        'Hay Ramzi',
        'Hay Shaker',
        'Iskan Al Batrawi',
        'Iskan Talal - Rusaifeh',
        'Jabal Al Abyad',
        'Jabal Al Ameer Hamza',
        'Jabal Al Ameer Hasan',
        'Jabal Al Ameer Rahma',
        'Jabal Al Mugheir',
        'Jabal El Shamali Rusaifeh ',
        'Jabal Tareq',
        'Jana\'a',
        'Khou',
        'Madinet El Sharq',
        'Qasr al-Hallabat Al-Gharbi',
        'Qasr al-Hallabat Al-Sharqi',
        'Rajm Al Shawk',
        'Rusaifeh El Janoobi',
        'Russayfah',
        'Sarout',
        'Shomer',
        'Um Rummanah',
        'Umm Sleih',
        'Wadi Al Aash',
        'Wadi Al Hajar',
        'Zarq Private University',
        'Other',
      ]
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0.0,
        centerTitle: true,
        leading: IconButton(
            icon: Icon(
              Icons.arrow_back,
              color: Colors.black,
            ),
            onPressed: () {
              setState(() {
                Navigator.push(context,
                    MaterialPageRoute(builder: (context) => MyPostHome()));
              });
            }),
        title: const Text(
          'Select City',
          style: TextStyle(
            fontWeight: FontWeight.bold,
            color: Colors.black,
          ),
        ),
        actions: [
          IconButton(
              icon: Icon(
                Icons.close,
                color: Colors.black,
              ),
              onPressed: () {
                showDialog(
                    context: context,
                    builder: (context) {
                      return AlertDialog(
                        title: Text('Exit Add Post'),
                        content: Text(
                            'Are you sure you want to cancel adding a post?'),
                        actions: [
                          TextButton(
                            onPressed: () => Navigator.pop(context, 'Cancel'),
                            child: Text('Cancel'),
                          ),
                          TextButton(
                            onPressed: () => Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => MyPostHome())),
                            child: Text('Yes'),
                          ),
                        ],
                        //child: const Text('Show Dialog'),
                      );
                    });
              }),
        ],
      ),
      body: Center(
        child: GridView.count(
          crossAxisCount: 1,
          padding: EdgeInsets.symmetric(horizontal: 50),
          mainAxisSpacing: 50,
          //crossAxisSpacing: 100,
          childAspectRatio: 3 / 2,
          children: [
            ..._items
                .map(
                  (item) => ClipRRect(
                    borderRadius: BorderRadius.circular(15),
                    child: InkWell(
                      onTap: () {
                        if (item['region'] != null) {
                          City.city = item['title'];
                          Navigator.of(context).push(MaterialPageRoute(
                              builder: (ctx) => Post4(
                                    region: item['region'],
                                    color: item['color'],
                                  )));
                        }
                      },
                      child: Container(
                        width: 200,
                        height: 200,
                        decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(15),
                            gradient: LinearGradient(
                                colors: [
                                  item['color'],
                                  item['color'].withOpacity(0.3),
                                ],
                                begin: Alignment.topLeft,
                                end: Alignment.bottomRight)),
                        child: Center(
                          child: Text(
                            item['title'],
                            style: TextStyle(
                                fontSize: 22, fontWeight: FontWeight.bold),
                          ),
                        ),
                      ),
                    ),
                  ),
                )
                .toList(),
          ],
        ),
      ),
    );
  }
}
